<?php
declare(strict_types=1);

/** Галерея загрузок: показывает использование и позволяет удалить только свободные файлы. */
require_once dirname(__DIR__) . '/include/app.php';
app_require_admin();
$pdo=app_pdo();$used=[];foreach($pdo->query("SELECT id,machine_number,address,photo_url FROM kiosks WHERE photo_url<>''")->fetchAll() as $row)$used[basename((string)$row['photo_url'])]=$row;
$directory=dirname(__DIR__).'/uploads/kiosks';$files=[];
foreach(glob($directory.'/kiosk-*.*')?:[] as $path){if(!is_file($path))continue;$name=basename($path);if(preg_match('/^kiosk-[a-f0-9]{24}\.(jpg|png|webp)$/',$name)!==1)continue;$files[]=['name'=>$name,'url'=>'/uploads/kiosks/'.$name,'size'=>(int)filesize($path),'used'=>$used[$name]??null];}
usort($files,static fn(array $a,array $b):int=>$b['size']<=>$a['size']);$total=array_sum(array_column($files,'size'));$unused=count(array_filter($files,static fn(array $f):bool=>$f['used']===null));
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Фотографии — Киосквода</title><link rel="stylesheet" href="/css/admin.css?v=20260816-5"></head><body><header class="admin-header"><div><strong>Киосквода</strong><span>Фотографии</span></div><nav><a href="/admin/">Панель владельца</a></nav></header><main class="admin-page"><div class="admin-page__heading"><div><p>Хранилище изображений</p><h1><?=count($files)?> файлов</h1></div><span><?=number_format($total/1048576,1,',',' ')?> МБ · <?=$unused?> свободных</span></div><?php if(!$files):?><p class="admin-notice">Загруженных фотографий пока нет.</p><?php else:?><div class="photo-gallery"><?php foreach($files as $file):?><article><img src="<?=app_h($file['url'])?>" alt="" loading="lazy"><div><strong><?=app_h($file['name'])?></strong><small><?=number_format($file['size']/1024,0,',',' ')?> КБ</small><?php if($file['used']):?><a href="/admin/?edit=<?=(int)$file['used']['id']?>">Используется: <?=app_h($file['used']['machine_number']?'№'.$file['used']['machine_number']:(string)$file['used']['address'])?></a><?php else:?><span class="unused-label">Не используется</span><form action="/admin/delete-photo.php" method="post" onsubmit="return confirm('Удалить свободный файл без возможности восстановления?');"><input type="hidden" name="csrf" value="<?=app_h(app_csrf())?>"><input type="hidden" name="name" value="<?=app_h($file['name'])?>"><button type="submit" class="danger">Удалить файл</button></form><?php endif;?></div></article><?php endforeach;?></div><?php endif;?></main></body></html>
