<?php
declare(strict_types=1);

/** Галерея загрузок: показывает использование и позволяет удалить только свободные файлы. */
require_once dirname(__DIR__) . '/include/app.php';
require_once dirname(__DIR__) . '/include/kiosk_admin.php';
app_require_admin();
$pdo=app_pdo();$used=[];foreach($pdo->query("SELECT id,machine_number,address,photo_url FROM kiosks WHERE photo_url<>''")->fetchAll() as $row)$used[basename((string)$row['photo_url'])]=$row;
$directory=dirname(__DIR__).'/uploads/kiosks';$files=[];
foreach(glob($directory.'/kiosk-*.*')?:[] as $path){if(!is_file($path))continue;$name=basename($path);if(preg_match('/^kiosk-[a-f0-9]{24}\.(jpg|png|webp)$/',$name)!==1)continue;$files[]=['name'=>$name,'url'=>'/uploads/kiosks/'.$name,'size'=>(int)filesize($path),'used'=>$used[$name]??null];}
usort($files,static fn(array $a,array $b):int=>$b['size']<=>$a['size']);$total=array_sum(array_column($files,'size'));$unused=count(array_filter($files,static fn(array $f):bool=>$f['used']===null));
$trashDirectory=dirname(__DIR__,2).'/private/runtime/photo-trash';$trash=[];
foreach(glob($trashDirectory.'/*')?:[] as $path){if(!is_file($path))continue;$name=basename($path);if(preg_match('/^\d{8}-\d{6}-[a-f0-9]{6}-(kiosk-[a-f0-9]{24}\.(?:jpg|png|webp))$/',$name,$match)!==1)continue;$trash[]=['name'=>$name,'original'=>$match[1],'time'=>(int)filemtime($path),'size'=>(int)filesize($path)];}
usort($trash,static fn(array $a,array $b):int=>$b['time']<=>$a['time']);
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Фотографии — Киосквода</title><link rel="stylesheet" href="/css/admin.css?v=20260901-1"></head><body><header class="admin-header"><div><strong>Киосквода</strong><span>Фотографии</span></div><nav><a href="/admin/">Панель владельца</a></nav></header><main class="admin-page"><div class="admin-page__heading"><div><p>Хранилище изображений</p><h1><?=count($files)?> файлов</h1></div><span><?=number_format($total/1048576,1,',',' ')?> МБ · <?=$unused?> свободных</span></div><?php if(isset($_GET['restored'])):?><p class="admin-success">Фотография восстановлена из корзины.</p><?php endif;?><?php if(!$files):?><p class="admin-notice">Загруженных фотографий пока нет.</p><?php else:?><div class="photo-gallery"><?php foreach($files as $file):?><article><img src="<?=app_h($file['url'])?>" alt="" loading="lazy"><div><strong><?=app_h($file['name'])?></strong><small><?=number_format($file['size']/1024,0,',',' ')?> КБ</small><?php if($file['used']):?><a href="/admin/?edit=<?=(int)$file['used']['id']?>">Используется: <?=app_h($file['used']['machine_number']?'№'.$file['used']['machine_number']:(string)$file['used']['address'])?></a><?php else:?><span class="unused-label">Не используется</span><form action="/admin/delete-photo.php" method="post" data-confirm="Переместить свободный файл в закрытую корзину на 30 дней?"><input type="hidden" name="csrf" value="<?=app_h(app_csrf())?>"><input type="hidden" name="name" value="<?=app_h($file['name'])?>"><button type="submit" class="danger">В корзину</button></form><?php endif;?></div></article><?php endforeach;?></div><?php endif;?><section class="photo-trash"><div class="admin-page__heading"><div><p>Можно вернуть в течение 30 дней</p><h2>Корзина фотографий</h2></div><span><?=count($trash)?> файлов</span></div><?php if(!$trash):?><p class="admin-notice">Корзина пуста.</p><?php else:?><div class="backup-list"><?php foreach($trash as $item):?><article><div><strong><?=app_h($item['original'])?></strong><small>Удалено <?=app_h(date('d.m.Y H:i',$item['time']))?> · <?=number_format($item['size']/1024,0,',',' ')?> КБ</small></div><form action="/admin/restore-photo.php" method="post"><input type="hidden" name="csrf" value="<?=app_h(app_csrf())?>"><input type="hidden" name="name" value="<?=app_h($item['name'])?>"><button class="secondary">Восстановить</button></form></article><?php endforeach;?></div><?php endif;?></section></main><script src="/js/admin-confirm.js?v=20260831-1" defer></script></body></html>
